---
- name: create user
  htpasswd:
    path: "{{ app.value.httpd.user.home }}/httpd/conf/htpasswd_{{ _vhost.key }}"
    name: "{{ _user.key }}"
    password: "{{ _user.value.password }}"
    state: "{{ _user.value.state | default('present') }}"
    mode: 0600
    owner: "{{ app.value.httpd.user.user }}"
  loop: "{{ _vhost.value.htpasswd_users|default({}) | dict2items }}"
  loop_control:
    loop_var: _user
